insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("GHIBLI", "Car",100000000, "MASERATI", 10, "스타일,파워,스포티한 핸들링,컴포트의 완벽한 조화")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("DISCOVERY", "Car", 76400000, "LAND ROVER", 27, "랜드로버 역사상 가장 다재다능한 suv")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("BMW i8", "Car", 150000000, "BMW", 5, "완벽한 오픈카 형태의 하이브리드 전기차")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("갤럭시 S20", "Phone", 900000, "삼성", 200, "갤럭시 시리즈 최신 핸드폰")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("아이폰 11 pro", "Phone", 3900, "apple", 230, "아이폰 시리즈 최신 핸드폰")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Pen S NT930SBE-K58", "Notebook", 1428000, "삼성", 21, "2배 향상된 S펜으로 더욱 완벽해진 노트북Pen S")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("그램17 17ZD90N-VX5BK", "Notebook", 1780000, "LG", 592, "모범생을 위한 노트북. LG 그램 17")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("SKW6451", "Clock",290000 , "스카겐", 18, "덴마크의 감성과 문화를 담은 디자인, 남성 가죽 손목시계")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("RL6A11QLUWO4R1", "Clock", 340000, "로만손", 120, "시계 전문 브랜드 로만손의 전문화된 A/S 시스템, 여성 전욕 손목시계")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("마이크로 GG 시마 중지갑", "Wallet", 593000, "구찌", 140, "브랜드 고유의 멋스러운 디자인으로 명품만의 디테일이 살아있어 더욱 고급스러운 매력적인 아이템")